name: Packer Build
on:
  push:
    branches:
      - main
      - dev
      - staging
      - prod
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, staging, prod]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils
          sudo usermod -aG libvirt,kvm $RUNNER_USER
          # We don't need newgrp commands in GitHub Actions as they run in separate shells
          
      - name: Install Packer Manually
        run: |
          PACKER_VERSION="1.9.2"
          wget https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip
          unzip packer_${PACKER_VERSION}_linux_amd64.zip
          sudo mv packer /usr/local/bin/
          packer version
          
      - name: Initialize Packer
        run: packer init packer/${{ matrix.environment }}.pkr.hcl
        
      - name: Validate Packer template
        run: packer validate packer/${{ matrix.environment }}.pkr.hcl
        
      - name: Build Images with Packer
        run: packer build -only=source.qemu.kvm packer/${{ matrix.environment }}.pkr.hcl